/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.project.recipeapp.data.models

import com.project.recipeapp.data.models.RecipeListItem

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param content 
 * @param page 
 * @param propertySize 
 * @param totalElements 
 * @param totalPages 
 */

data class RecipeListResponse (

    @Json(name = "content")
    val content: kotlin.collections.List<RecipeListItem>,

    @Json(name = "page")
    val page: kotlin.Int,

    @Json(name = "size")
    val propertySize: kotlin.Int,

    @Json(name = "totalElements")
    val totalElements: kotlin.Int,

    @Json(name = "totalPages")
    val totalPages: kotlin.Int

) {


}

